version: "1.0"
stages:
    - "clone"
    - "build"
    - "integration"
    - "push"
    - "deploy"
steps:
    main_clone:
        type: "git-clone"
        description: "Cloning main repository..."
        repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
        revision: '${{CF_REVISION}}'
        stage: "clone"
    build:
        title: "Building Docker Image"
        type: "build"
        image_name: "wohlig-framework"
        tag: "${{CF_BRANCH}}"
        dockerfile: "Dockerfile"
        stage: "build"
    push:
        title: "Pushing image to ECR"
        type: "push"
        image_name: "wohlig-framework"
        registry: "uprose-ecr"
        candidate: "${{build}}"
        tags:
            - "${{CF_BRANCH}}"
        stage: "push"
    deploy:
        title: Running Deploy Script
        type: deploy
        kind: kubernetes
        cluster: UproseFinmart
        namespace: production
        service: wohlig-framework
        candidate:
            image: "${{build}}"
            registry: uprose-ecr
        stage: "deploy"
